name: Regenerate site
on:
  schedule:
    - cron: '30 * * * *'

jobs:
  regenerate:
    name: Regenerate site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Regenerate site
        run: |
          #
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated sync
